sample(c("Johnny","Waylon","Willie","Kris"))
sample(c("Rahul","Ramesh","Rakesh","Rudresh"))
getwd(women)
setwd(women)
Ritesh_mydata<-women
return(Ritesh_mydata)
Ritesh_data (Ritesh_mydata,2)
Ritesh_mydata (Ritesh_mydata,2)
returnValue(Ritesh_mydata,2)
wt(Ritesh_mydata,2)
topenv(Ritesh_mydata,2)
filter(Ritesh_mydata,2)
head(Ritesh_mydata,2)
str(Ritesh_mydata)
summary(Ritesh_mydata)
mean(Ritesh_mydata$height)
Just_Height<- (Ritesh_mydata$height)
Just_weight<- (Ritesh_mydata$weight)
HeightandWeight <-data.frame(Just_eight, Just_Weight)
HeightandWeight <-data.frame(Just_Height,Just_Weight)
HeightandWeight <-data.frame(Just_Height, Just_weight)
subset(HeightandWeight, Just_Height>65)
df.shape (HeightandWeight)
df(HeightandWeight)
df.columns(HeightandWeight)
nrow(HeightandWeight)
ncol(HeightandWeight)
install.packages("tibble")
library(tibble)
NewWomen<-tibble(HeightandWeight, height=Just_Height, weight=Just_weight)
NewWomen1<-tibble(height=Just_Height, weight=Just_weight)
View(NewWomen)
View(NewWomen1)
#Newwomen: Creates same column and rows similar to the just height and just weight.And name as height and weight.
#Newwomen1: Creates same column and row similar to the just height and weight.and removed just height and just weight column.
install.packages("ggplot2")
library(ggplot2)
ggplot(NewWomen, aes(x=height, y=weight)) + 
  geom_point()
ggplot(NewWomen, aes(x=height, y=weight)) + 
  geom_point(shape = 21, colour = "black", fill = "white", size = 5, stroke = 5)
#I can see plots looks bigger than before with black and white color and size increases.